version: '3.8'

services:
  seeker:
    build: .
    container_name: seeker
    command: -t 1
    ports:
      - "8080:8080"
    networks:
      - ngroknet
    tty: true
    stdin_open: true

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http seeker:8080
    environment:
      NGROK_AUTHTOKEN: "3DjNKorbWaT0exqSTgvCEjSzyOx_5uYm9cxh7MDKnN8sf8RY3"
    networks:
      - ngroknet
    ports:
      - "4040:4040"
    depends_on:
      - seeker

networks:
  ngroknet:
    driver: bridge
